site_name: Jacob Distributed Message System Book
site_description: "Jacob's 分布式系统技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Kafka 技术详解':
    - '第一节 Kafka设计介绍': '1kafka/1chap1_kafka.md' 
    - '第二节 Kafka中的关键术语解释': '1kafka/2chap1_terminology.md' 
    - '第三节 Kafka的工作原理和过程': '1kafka/3chap1_process.md' 
    - '第四节 Kafka 集群搭建': '1kafka/4chap1_install.md'
    - '第五节 Kafka API': '1kafka/5chap1_API.md'
    - '第六节 图解 Kafka': '1kafka/6chap1_chater.md'
    - '第七节 Kafka 宕机引发的高可用问题': '1kafka/7chap1_kafka_ha.md'
    - '第八节 面试必问的 kafka 知识点': '1kafka/8chap1_kafka_int1.md'
    - '第九节 Kafka经典面试题详解': '1kafka/9chap1_kafka_int2.md'
  - 'Kafka K8S&Opt':
    - 'L1 在 Kubernetes 上运行高可用的 Kafka 集群': '2kafka/1kafka_k8s.md'
    - 'L2 Kafka实战—常见运维操作': '2kafka/2kafa_opt1.md'  



repo_url: https://github.com/Chao-Xi/jxdmsbook.git
repo_name: "jxdmsbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'indigo'
  i18n:
    prev: 'Previous'
    next: 'Next'