site_name: Jacob Distributed Message System Book
site_description: "Jacob's 分布式系统技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: "https://chao-xi.github.io/jxdmsbook/"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Kafka 核心技术':
    - 'Chap1 Kafka 入门': 'chap_ka1/1kafka_intro.md'
    - 'Chap2 kafka基本部署参数': 'chap_ka1/2kafa_setup.md'
    - 'chap3 客户端实践及原理1': 'chap_ka1/3kafa_client1.md'
    - 'chap4 客户端实践及原理2': 'chap_ka1/4kafka_client2.md'
    - 'Chap5 Kafka 内核': 'chap_ka1/5kafka_core.md'
    - 'Chap6 Kafka 管理&工具脚本': 'chap_ka1/6kafka_mgt.md'
  - 'Kafka 技术详解':
    - '第一节 Kafka设计介绍': '1kafka/1chap1_kafka.md' 
    - '第二节 Kafka中的关键术语解释': '1kafka/2chap1_terminology.md' 
    - '第三节 Kafka的工作原理和过程': '1kafka/3chap1_process.md' 
    - '第四节 Kafka 集群搭建': '1kafka/4chap1_install.md'
    - '第五节 Kafka API': '1kafka/5chap1_API.md'
    - '第六节 图解 Kafka': '1kafka/6chap1_chater.md'
    - '第七节 Kafka 宕机引发的高可用问题': '1kafka/7chap1_kafka_ha.md'
    - '第八节 面试必问的 kafka 知识点': '1kafka/8chap1_kafka_int1.md'
    - '第九节 Kafka经典面试题详解': '1kafka/9chap1_kafka_int2.md'
    - '第十节 RabbitMQ和Kafka的比较': '1kafka/10kafka_rabbitmq.md'
    - '第十一节 5 分钟搞懂高性能分布式消息系统 Kafka': '1kafka/11chap1_kafka_5min.md'
  - 'Kafka K8S&Opt':
    - 'L1 在 Kubernetes 上运行高可用的 Kafka 集群': '2kafka/1kafka_k8s.md'
    - 'L2 Kafka实战—常见运维操作': '2kafka/2kafa_opt1.md'
    - 'L3 kafka应用经验': '2kafka/3kafka_opt2.md'
  - '分布式链路追踪':
    - '1 数据观测：数据追踪的基石': '3track_mon/1data_mon.md'
    - '2 系统稳定性的关键系统日志&编写可观测的日志': '3track_mon/2log_setup.md'
  - 'Serverless 技术':
    - 'L1 Serverless 价值与机构': '4serverless/1Serverless_intro.md'
    - 'L2 Serverless 函数的简介': '4serverless/2functions.md'
  - 'dapr Distributed Application Runtime':
    - '1 Dapr 入门教程': 'dapr/1dapr_intro.md'
    - '2 Dapr 入门教程之发布订阅': 'dapr/2dapr_pub_sub.md'
    - '3 Dapr 入门教程之消息队列': 'dapr/3dapr_msg.md'
    - '4 Dapr 可观测性之分布式追踪': 'dapr/4dapr_tracing.md'
    - '5 Dapr 可观测性之指标与日志': 'dapr/5dapr_mon.md'
    - '6 Dapr 入门教程之密钥存储': 'dapr/6dapr_sec.md'
    - '7 Dapr 入门教程之中间件': 'dapr/7dapr_middle.md'


repo_url: https://github.com/Chao-Xi/jxdmsbook.git
repo_name: "jxdmsbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'indigo'
  i18n:
    prev: 'Previous'
    next: 'Next'